name: CI Pipline
on: 
  push:
  pull_request:
jobs:
  prepare-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4    

        -name: checkout code
        uses: actions/checkout@v4

        -name: chache node modules
        id: node-modules-cache
        uses: actions/cache@v4  
        with:
         path: node_modules
         key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
          ${{ runner.os }}-node-modules-
        -nam: install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci